### ISSUE TITLE
[CHORE] The walkthrough appears to be outdated (v1.6.14)

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/phoenix-chat-example#112]
As of the time of writing, Phoenix's latest version is **`1.6.14`** (with **`1.7`** apparently coming very soon 🤩 ). 
This tutorial is great and works perfectly if I clone and run it.

However, when I try to build a **`new` `Phoenix` app** from scratch and follow this tutorial, 
some information appears to be outdated. 

Here are a few examples:

- [ ] The boostrapped project with the newest version appears to have more files in some folders, namely `lib\templates\layout`.
- [ ] Updating the layout template on `app.html.eex` does not make sense now, since the information is on `root.html.eex`.
- [ ] Tests do not pass after "correcting" in `page_controller_test.exs`.

This is a snowball effect and for anyone that is **`new`**, they expect this tutorial to "**Just _Work_**<sup>TM</sup>". 
No doubt it does with v.1.6.11, though!

I'll try to update the tutorial to the latest version and the README file accordingly to the best of my abilities 😄 ...

# Todo

+ [x] **`clone`** the repo to localhost ⬇️ 
+ [x] make a _reference_ copy of the repo e.g. **`cp phoenix-chat-example phoenix-chat-example_OLD`** so that you can have one open while editing the other and not have to switch between branches.  ✌️ 
> **Note**: this is where having that second or ***third*** screen comes into play. 💻 + 🖥️ + 🖥️  💭 
+ [x] Create a new branch e.g. **`rewrite-phoenix-v1.6.14-issue#112`** (snappy name, right? 😜)
  + [x] **`git push`** the new branch to GitHub ASAP so that you can see if **CI** (GitHub Actions) continues to pass.
+ [x] Re-create the app from scratch following the instructions in the `README.md` as much as possible. 🧑‍💻 
+ [x] Update the sections that require it. 🆙 
+ [x] Preserve the Testing and any other sections that are still relevant. 🥇 
+ [x] Create a PR and assign it to me for review. 🙏

**Comment by nelsonic** [comment]
@LuchoTurtle thank you very much for opening this issue. 🎉 
I periodically go through the tutorials with the latest version of Phoenix and make adjustments. 📝 
But I haven't done it _properly_ for a few versions ... ⏳ 🙄 

Sounds like we need to treat the _existing_ code as a reference
 and essentially re-do it from scratch with a full `mix phx.new` ... 

That being the case, I've updated the OP to reflect the work that needs to be done. 💭

**Comment by LuchoTurtle** [comment]
@nelsonic consider changing the description to `💬 A Step-by-Step Beginners Tutorial for Building, Testing & Deploying a Chat app in Phoenix 1.6.14🚀` 😉

**Comment by nelsonic** [comment]
@LuchoTurtle you should have access to make the update. if not, please LMK. 👍
