### ISSUE TITLE
Add `Tailwind CSS` ✨ 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-chat-example#121]
It's occurred to me that the CSS/Styles in this example are "meh" ...

<img width="952" alt="image" src="https://user-images.githubusercontent.com/194400/202434677-6bb6aea0-1f94-42a1-9ff2-ee11d37a42e5.png">

And with the addition of **`Tailwind CSS`** in **`Phoenix 1.7`** https://github.com/dwyl/learn-phoenix-framework/issues/152
We can _significantly_ improve the UI! 

Luckily, we've already done the "hard" part in: [dwyl/phoenix-liveview-chat-example#15-**tailwind-css-stylin**](https://github.com/dwyl/phoenix-liveview-chat-example/tree/eabe4be121061b213a70159248c4869cdb8335ac#15-tailwind-css-stylin)

![liveview-chat-with-tailwind](https://user-images.githubusercontent.com/194400/174119023-bb83f5f4-867c-4bfa-a005-26b39c700137.gif)

So I _expect_ that we can _borrow_ much of the code from that tutorial 
and _estimate_ that it shouldn't take us more than **`T1h`** to get it done. 
(_probably much less Time/Effort, but being conservative for any layout issues ..._)

# Todo

+ [x] Add docs section to Main `README.md` for adding `Tailwind`
+ [x] Add `Tailwind CSS` to this `Phoenix 1.6.x` project _manually_
+ [x] Attempt to borrow the code from: https://github.com/dwyl/phoenix-liveview-chat-example/blob/main/lib/liveview_chat_web/templates/layout/root.html.heex
+ [x] Adapt as needed

**Comment by nelsonic** [comment]
Included in: #120

**Comment by nelsonic** [comment]
@LuchoTurtle please include a screenshot of the finished thing in the issue before assigning it back to me.

**Comment by LuchoTurtle** [comment]
Sorry about that. 

It should look like this.

<img width="925" alt="image" src="https://user-images.githubusercontent.com/17494745/203308263-fb867c9b-3ab6-4557-a361-03330d23bcf8.png">

**Comment by nelsonic** [comment]
Sorry for not being clear.
The desired UI/UX is already in the OP. 
This layout you've created certainly looks _good_. 👍 
By all means add it to your Dribbble account: https://dribbble.com/tags/messaging
but it's over-thinking it by having the message box off to the right ... 🤷‍♂️ 
and doesn't _look_ "mobile first" (i.e. "boring") ... 📱 
Unless the mobile is a Tablet. 💭 

I'm all for creating design variations and A-B testing them once we have a testing framework in place. 🆎 
Until then we need to keep the designs as Boring (AF!) as possible even if it means that it "looks the same" as every other app that does something similar. 

If even _one_ non-technical person ***ever*** has to ask themself "Why is that there?"
 or "Where is the ...?" then we have failed to build an intuitive interface.

I _get_ that this way on a larger screen the person can see more of the message history. ✅ 
But you need to see this from perspective of the person who isn't _used_ to seeing this layout 
and doesn't see the immediate benefit and just thinks "Why...?" 🤷‍♂️

**Comment by nelsonic** [comment]
For the avoidance of all future doubt: https://en.wikipedia.org/wiki/Occam's_razor

**Comment by LuchoTurtle** [comment]
Changed it to look like so.
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/17494745/203333181-73fd07a8-c78d-49ad-a13d-06248109574e.png">

Waiting for a response on https://github.com/dwyl/phoenix-chat-example/pull/120#issuecomment-1323626395
👀

**Comment by LuchoTurtle** [comment]
https://github.com/dwyl/phoenix-chat-example/pull/120#issuecomment-1325094372

Going to assign this for review, with the login issue resolved 👍

**Comment by nelsonic** [comment]
Believe we can close this issue now as `Tailwind` is indeed in the PR we colab'd on: #120 ✅ 
Thanks again @LuchoTurtle 👌

**Comment by nelsonic** [comment]
***`before`***:
![image](https://user-images.githubusercontent.com/194400/204512127-562f4c82-38cd-4a2d-a172-d897fd3c6f0d.png)

**Comment by LuchoTurtle** [comment]
Shouldn't this be open until https://github.com/dwyl/phoenix-chat-example/pull/120  is merged?

**Comment by nelsonic** [comment]
Merged. ✅
