### ISSUE TITLE
Chore: Migrate demo app from Heroku to Fly.io

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-chat-example#122]
In light of Heroku discontinuing "hobby" apps https://github.com/dwyl/learn-heroku/issues/52
We are migrating our apps off Heroku to Fly.io

# Todo

+ [x] Create new `org` for the demo app on Fly.io
+ [x] Create new `app` 
+ [x] Deploy the app using `fly launch`
+ [x] Update the docs in the `README.md`

**Comment by nelsonic** [comment]
https://fly.io/dashboard/dwyl-phoenix-chat-example
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/194400/202456285-58441d66-403d-4979-a09e-3d00ca5ba2ce.png">

https://phoenix-chat.fly.dev/
![image](https://user-images.githubusercontent.com/194400/202456512-8db02945-bf0a-46fe-9d8c-6818228d7b6c.png)

https://github.com/dwyl/phoenix-chat-example/settings/secrets/actions
![image](https://user-images.githubusercontent.com/194400/202457122-b8e3df5e-f69d-40e1-a92f-e9542275a492.png)

Auto-deploy should work. 👌 

# Next: https://github.com/dwyl/phoenix-chat-example/issues/121

**Comment by nelsonic** [comment]
Included in #120 ✅
