### ISSUE TITLE
Chore: Remove `swoosh` from phoenix chat example [not used/needed]

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-chat-example#132]
This project is not using **`swoosh`**: https://hex.pm/packages/swoosh 
Let's remove it and any email-sending related code from the project.

# Todo

+ [ ] Remove **`swoosh`** from `mix.exs` and `mix.lock` ✂️ 
+ [ ] Remove any [unused] code/config that would have used it. 🔪 
+ [ ] Create a Pull Request 🆕 
+ [ ] Have a great day! ☀️
