### ISSUE TITLE
Chore: Comprehensively Update this Tutorial to `Phoenix v1.7`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-chat-example#149]
With the recent release of [`Phoenix v1.7.0-rc.2`](https://github.com/phoenixframework/phoenix/releases/tag/v1.7.0-rc.2) (which looks reasonably stable),
Now is a good time to _comprehensively_ update this tutorial to the latest and greatest.
This is a great opportunity for us to see the differences between `1.6.X` and `1.7` in a more involved project.

# Todo

+ [x] `git clone` this project to your `localhost` and rename it to `phx-chat-OLD`
+ [x] use this "old" version as the basis for creating the new one, but ...
+ [x] `git clone` the project _again_ and then ***`DELETE`*** all the code in the directories and `mix.exs`/`mix.lock` file:

<img width="1072" alt="phoenix-chat-example-delete" src="https://user-images.githubusercontent.com/194400/216367795-7550abdd-3070-4036-b9b8-8539cf12b864.png">

+ [x] Create a new branch on your `localhost` e.g. `phx-1.7-issue#X` and 
+ [x] Follow the instructions in the `REAMDE.md` to create a new app from scratch.
+ [x] Please remember to exclude all the noise that we don't need in a demo app like this e.g:

```sh
mix phx.new chat --no-mailer --no-dashboard --no-gettext
```

We _really_ don't need all the noise from constant @dependabot updates for `deps` we aren't using in the example! ⏳ 

> **Note**: this tutorial will ***NOT*** use `LiveView`. 
We have a different one for that: https://github.com/dwyl/phoenix-liveview-chat-example
That is deliberate. We still use "MVC" (even though `Phoenix` has removed the "V" ... https://www.germanvelasco.com/blog/phoenix-1-7-is-view-less ... 🙄 )
So we want `this` tutorial to continue to showcase the `M🙃C`   workflow even if we use `LiveView` in some other places.
I have _zero_ intention of using `LiveView` for the basic flow in `Auth` for example. It's just not appropriate. 

+ [x] Update the `README.md` as needed to match the updates in `Phoenix`.
+ [x] Match all the features in the current example including the `Tailwind` UI/UX and `auth` 
  + [x] update `auth.md` as needed (shouldn't be too much)
+ [x] Create a Pull Request with the update.
+ [x] Review your own PR ***`before`*** assigning it for review.
+ [x] Assign the PR to @SimonLab for review. 🙏 

I expect this update to take a few hours. (**`T4h`**? 🤷‍♂️)
It _pains_ me that we have to spend this time. I _wish_ there weren't so many **_breaking_ changes**! 😢 
But the _faster_ we can make this update the faster I (@nelsonic) can learn what I need to re-build `auth` https://github.com/dwyl/auth/issues/207 🤞 

Thanks! 🙏

**Comment by nelsonic** [comment]
PR: https://github.com/dwyl/phoenix-chat-example/pull/152 :shipit:
