### ISSUE TITLE
UI Bug: Message input field overlaps last message in thread

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-chat-example#151]
At present the final message in the thread is covered by the input:

<img width="921" alt="chat-example-input-covers-final-message" src="https://user-images.githubusercontent.com/194400/216542735-82e9fd18-1324-48d0-abde-11a29335f6a6.png">

This is the very definition of a "not fun" UI bug to fix ...
But equally researching and _understanding_ how to fix it is a great test of Tailwind/CSS knowledge. 

# Todo

+ [ ] Add `Tailwind` class to ensure that the `<input #msg>` does not cover the message(s)
+ [ ] Check that it works on Mobile Device. 
+ [ ] Create PR to update.
+ [ ] Assign PR. 

Video showing the issue in more detail:
https://user-images.githubusercontent.com/194400/216541869-df66058b-e81a-49b4-98a9-6dea11bfc73f.mov

Again, if you're in any doubt ***Why*** we build such comprehensive tutorials/examples,
we do it because it's the "right thing" to do for other people who are learning our [Tech Stack](https://github.com/dwyl/technology-stack#the-petal-stack)
And the _practice_ makes us _much_ better at our jobs. 
Learning is 60% of knowledge work. The better you are at _capturing_ what you learn the more valuable you are.
Some companies think it's "OK" for their people to hold all the knowledge in their heads. we take the opposite view.
we want as _many_ people both in our team and the wider community to know how to build and fix things. 

So _thank you_ for looking at this bug. 🙏
