### ISSUE TITLE
Update version of Phoenix in "Before you Start" section

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-chat-example#21]
At present the version of Phoenix recommended in the `README.md` is **`1.4.0`** (_so last year!_)
![image](https://user-images.githubusercontent.com/194400/57133039-8036a700-6d99-11e9-8a7e-ed849b87fdba.png)

The latest version according to https://github.com/phoenixframework/phoenix/releases is **`1.4.4`**:
![image](https://user-images.githubusercontent.com/194400/57133129-c8ee6000-6d99-11e9-9fe2-b2b4e3b49ba1.png)

The recommended way of installing Phoenix is still the mix task:
```
mix archive.install hex phx_new 1.4.4
```
https://hexdocs.pm/phoenix/installation.html
![image](https://user-images.githubusercontent.com/194400/57133077-9e040c00-6d99-11e9-9298-d29c12c00571.png)

# Todo

+ [x] Update version Phoenix in `README.md` installation instructions
+ [x] Update version of Phoenix `mix.exs` including any dependencies. 
(_I created a new `chat` app on my `localhost` to check if there are any other changes_)
```elixir
  defp deps do
    [
      {:phoenix, "~> 1.4.4"},
      {:phoenix_pubsub, "~> 1.1"},
      {:phoenix_ecto, "~> 4.0"},
      {:ecto_sql, "~> 3.0"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.11"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:gettext, "~> 0.11"},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"}
    ]
  end
```
+ [x] Create Pull Request with Changes.
