### ISSUE TITLE
Elm + Phoenix Quest

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-chat-example#26]
We _love_ Elixir & Phoenix because they make building web apps easy and fun!
We are _less_ enamoured with using JavaScript on the frontend because reliability is _hard_ in JS.

At present there is not very much JS in this example because features are minimal, see: [`app.js`](https://github.com/dwyl/phoenix-chat-example/blob/754ce403063635d14b5964bd681a4cd6c53930d6/assets/js/app.js)
but the more JS we add the more likely it is to get messy and unmaintainable. 

So I propose we _extend_ this tutorial using `Elm` instead of JS 
and give people a basic intro to `Elm` as the "advanced" section of this example. 

# Todo

Extend this tutorial to use Elm on the frontend for extensibility/reliability.

+ [ ] Add **GitHub Auth** to avoid impersonation and anonymous vandalism. see: https://github.com/dwyl/phoenix-chat-example/issues/25 
  `|>` https://github.com/dwyl/elixir-auth-github/issues/32
+ [ ] Add Phoenix Presence (server side) to see who is online: https://github.com/dwyl/phoenix-chat-example/issues/14
  + [ ] Use Elm to display the list of people who are online with GitHub Profile pictures
    + [ ] When profile pic hovered over or clicked display more profile details, e.g:
![image](https://user-images.githubusercontent.com/194400/62926520-94cd0700-bdac-11e9-802c-3f7b807bd4dc.png)
+ [ ] Use Elm to post messages and avoid XSS by _sanitising_ user input #25
+ [ ] Create a "Connected Status" Icon in the UI which shows when connected/disconnected.
  + [ ] Detect when disconnected from Phoenix server/channel. 
    e.g: if I turn off Wifi on my device, the UI should reflect that I am no longer connected and change the "connected" icon to https://thenounproject.com/term/no-connection/369426/
  + [ ] disable the "post" message action, but should still allow messages to be composed.
  + [ ] When re-connected to Phoenix, display a brief and unobtrusive "connected" ([snackbar](https://material.io/design/components/snackbars.html)) message and update the icon to show "Online" version.
