### ISSUE TITLE
Feat: Add `auth_plug` to Phoenix Chat Example so people can authenticate 🔐 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-chat-example#54]
This tutorial is currently _already_ quite [popular](https://github.com/dwyl/phoenix-chat-example/stargazers). 🤩 🎉 
We can take it to the **_next_ level** by adding **`auth`** via [**`auth_plug`**](https://github.com/dwyl/auth_plug) using **`ONE Environment Variable™`**! 🚀 

# Story

As a **`person`** learning **`Elixir/Phoenix`** 🌱 
**I need** a **_fully_ featured example** including **`auth`** 🔐 
**So _that_** I can **learn** the [**`Tech Stack`**](https://github.com/dwyl/technology-stack) as _fast_ as possible and contribute in the team. 🙌 

@LuchoTurtle hopefully you can identify with this story. 🤞 

# Todo

+ [x] Create a new markdown file called `auth.md` and link to it from the main `README.md`
+ [x] Document each step in the setup process for adding authentication to this Chat App.
+ [x] Add [**`auth_plug`**](https://github.com/dwyl/auth_plug) to this project, see: https://github.com/dwyl/auth_plug_example#how
  + [ ] Along the way, if you get stuck, _please_ open issues! 🙏
> Our objective is to make all our docs "standalone"; i.e. anyone can pick up and understand _exactly_ what is going on without hitting any hurdles. We _acknowledge_ that we aren't there [_yet_](https://xkcd.com/1513/): https://github.com/dwyl/auth/issues/153#issuecomment-945662561 so we need _lots_ of help to get to the point where `auth` has _superb_ documentation. 
+ [x] Figure out if `conn.assigns.person` is available in a Channel (JS) request for channels.
+ [x] Add Tailwind for Layout/Styling see: [github.com/dwyl/learn-tailwind#part-2-tailwind-in-phoenix](https://github.com/dwyl/learn-tailwind#part-2-tailwind-in-phoenix)

Very happy to [_pair_](https://en.wikipedia.org/wiki/Pair_programming) on this if you want an idea of my workflow.

Hopefully this is a fun challenge that will help you to learn a bit of the [**`Tech Stack`**](https://github.com/dwyl/technology-stack) 🤞 
and make it a _lot_ easier for the [_next_](https://blog.codinghorror.com/coding-for-violent-psychopaths/) people joining the team. 😉 

![image](https://user-images.githubusercontent.com/194400/195295873-cc00c56e-67be-4d79-9449-7687546c63ea.png)

**Comment by nelsonic** [comment]
Ref: https://github.com/dwyl/phoenix-liveview-chat-example#12-authentication

**Comment by nelsonic** [comment]
https://authdemo.fly.dev/apps

**Comment by nelsonic** [comment]
@LuchoTurtle PR: #120 should be good for you to continue/finish. 🙏

**Comment by nelsonic** [comment]
Done! #120 🎉

**Comment by nelsonic** [comment]
https://github.com/dwyl/phoenix-chat-example/blob/main/auth.md
