### ISSUE TITLE
Update to Phoenix v1.6

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-chat-example#55]
Given the recent Phoenix [v1.6.0-rc.1](https://github.com/phoenixframework/phoenix/blob/8d1fa447c21c7a607be95d540360d64bf5aba173/CHANGELOG.md#160-rc1) see: https://github.com/dwyl/learn-phoenix-framework/issues/143

# Todo

+ [x] Go through this tutorial again and update to the latest Phoenix 
  + [x] Confirm if there is any added complexity or if v1.6 simplifies things. 
+ [x] Create Pull Request with changes
+ [x] Assign PR for review

I expect this exercise to take around **`T2h`** because the tutorial is quite long and we need to test all the steps.
It might take less time, but this is the estimate. 💭

**Comment by nelsonic** [comment]
Read through the upgrade guide: https://gist.github.com/chrismccord/2ab350f154235ad4a4d0f4de6decba7b
Looks fairly straightforward. 
I'm still holding off doing it until more edge cases are ironed out so I don't have to waste too much time.

**Comment by nelsonic** [comment]
We've now updated quite a few of our Apps to Phoenix **`1.6** without any issues: 🚀 
+ [x] `auth`: https://github.com/dwyl/auth/pull/147
+ [x] `auth_plug_example`: https://github.com/dwyl/auth_plug_example/pull/13
+ [x] `elixir-auth-google-demo` https://github.com/dwyl/elixir-auth-google-demo/pull/7

Fairly certain we could tackle this issue/update now. 💭 
@ajmeese7 if you're keen to dive in - very much appreciated - let us know how you get on. 
(You should have write-access, please create a PR. Thanks!)

**Comment by nelsonic** [comment]
Working on `localhost`:
![image](https://user-images.githubusercontent.com/194400/137472547-ec2be248-322d-4ac7-a667-8d4165d4cf25.png)

**Comment by nelsonic** [comment]
Replaced Travis-CI with GitHub Actions: https://github.com/dwyl/phoenix-chat-example/pull/63 ✅
